#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#    Apr 20, 2019 05:50:14 PM IST  platform: Linux

import sys
from functools import partial

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import cancel_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Cancel_Toplevel (root)
    cancel_support.init(root, top)
    root.mainloop()

w = None
def create_Cancel_Toplevel(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Cancel_Toplevel (w)
    cancel_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Cancel_Toplevel():
    global w
    w.destroy()
    w = None

class Cancel_Toplevel:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("400x200+476+276")
        top.title("Cancel")
        top.configure(background="#dbdbdb")
        top.configure(highlightcolor="#d8d8d8")

        self.Cancel_Label = tk.Label(top)
        self.Cancel_Label.place(relx=0.175, rely=0.25, height=28, width=241)
        self.Cancel_Label.configure(activebackground="#f9f9f9")
        self.Cancel_Label.configure(background="#ff1239")
        self.Cancel_Label.configure(text='''Are you sure you want to cancel order?''')

        self.Cancel_Button = tk.Button(top)
        self.Cancel_Button.place(relx=0.388, rely=0.6, height=28, width=69)
        self.Cancel_Button.configure(activebackground="#f9f9f9")
        self.Cancel_Button.configure(background="#000000")

        cancel_handler = partial(cancel_support.cancel_handler, self, top)

        self.Cancel_Button.configure(command=cancel_handler)
        self.Cancel_Button.configure(text='''Cancel''')

if __name__ == '__main__':
    vp_start_gui()





