#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#    Apr 19, 2019 06:34:06 PM IST  platform: Linux

import sys
from functools import partial

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import invalid_size_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Invalid_Size (root, None)
    invalid_size_support.init(root, top)
    root.mainloop()

w = None
def create_Invalid_Size(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Invalid_Size (w, None)
    invalid_size_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Invalid_Size():
    global w
    w.destroy()
    w = None

class Invalid_Size:
    def __init__(self, top=None, win=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("300x100+540+293")
        top.title("Error")
        top.configure(background="#ff243a")
        top.configure(highlightcolor="black")

        self.Invalid_Label = tk.Label(top)
        self.Invalid_Label.place(relx=0.133, rely=0.2, height=18, width=205)
        self.Invalid_Label.configure(activebackground="#fcfcfc")
        self.Invalid_Label.configure(background="#4f4f4f")
        self.Invalid_Label.configure(text='''Invalid size''')

        self.Invalid_OK_Button = tk.Button(top)
        self.Invalid_OK_Button.place(relx=0.4, rely=0.55, height=28, width=45)
        self.Invalid_OK_Button.configure(activebackground="#f9f9f9")
        self.Invalid_OK_Button.configure(background="#969696")

        invalid_size_handler = \
        partial(invalid_size_support.invalid_size_handler, self, top, win)

        self.Invalid_OK_Button.configure(command=invalid_size_handler)
        self.Invalid_OK_Button.configure(text='''OK''')

if __name__ == '__main__':
    vp_start_gui()





