#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#    Apr 19, 2019 11:51:58 AM IST  platform: Linux

import sys
from functools import partial

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import login_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Login_Toplevel (root)
    login_support.init(root, top)
    root.mainloop()

w = None
def create_Login_Toplevel(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    # w = tk.Toplevel (root)
    top = Login_Toplevel (rt)
    login_support.init(rt, top, *args, **kwargs)
    return top

def destroy_Login_Toplevel():
    global w
    w.destroy()
    w = None

class Login_Toplevel:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("600x450+441+156")
        top.title("Login")
        top.configure(background="#000000")
        top.configure(highlightcolor="black")

        self.Username_Entry = tk.Entry(top)
        self.Username_Entry.place(relx=0.275, rely=0.311, height=20
                , relwidth=0.41)
        self.Username_Entry.configure(background="#919191")
        self.Username_Entry.configure(font="TkFixedFont")
        self.Username_Entry.configure(selectbackground="#c4c4c4")

        self.Username_Label = tk.Label(top)
        self.Username_Label.place(relx=0.275, rely=0.278, height=18, width=246)
        self.Username_Label.configure(activebackground="#f9f9f9")
        self.Username_Label.configure(background="#5b5b5b")
        self.Username_Label.configure(foreground="#ffffff")
        self.Username_Label.configure(text='''Username''')

        self.Signup_Button = tk.Button(top)
        self.Signup_Button.place(relx=0.275, rely=0.567, height=28, width=111)
        self.Signup_Button.configure(activebackground="#ccc8cc")
        self.Signup_Button.configure(background="#353535")
        
        signup_handler = partial(login_support.signup_handler, self, top)

        self.Signup_Button.configure(command=signup_handler)
        self.Signup_Button.configure(text='''Signup''')

        self.Password_Entry = tk.Entry(top)
        self.Password_Entry.place(relx=0.275, rely=0.456, height=20
                , relwidth=0.41)
        self.Password_Entry.configure(background="#919191")
        self.Password_Entry.configure(font="TkFixedFont")
        self.Password_Entry.configure(selectbackground="#c4c4c4")
        self.Password_Entry.configure(show="*")
        
        self.Login_Button = tk.Button(top)
        self.Login_Button.place(relx=0.5, rely=0.567, height=28, width=111)
        self.Login_Button.configure(activebackground="#ccc8cc")
        self.Login_Button.configure(background="#353535")

        login_handler = partial(login_support.login_handler, self, top)

        self.Login_Button.configure(command=login_handler)
        self.Login_Button.configure(text='''Login''')


        self.Password_Label = tk.Label(top)
        self.Password_Label.place(relx=0.275, rely=0.422, height=18, width=246)
        self.Password_Label.configure(activebackground="#f9f9f9")
        self.Password_Label.configure(background="#5b5b5b")
        self.Password_Label.configure(foreground="#ffffff")
        self.Password_Label.configure(text='''Password''')

if __name__ == '__main__':
    vp_start_gui()





