#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#    Apr 12, 2019 11:23:23 AM IST  platform: Linux
#    Apr 12, 2019 11:27:01 AM IST  platform: Linux

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def modify_cancel_handler(top, root):
    # print('modify_support.modify_cancel_handler')

    root.destroy()

    sys.stdout.flush()

def modify_ok_handler(top):
    print('modify_support.modify_ok_handler')

    '''
    symbol = top.Symbol_Entry.get()
    size = top.Size_Entry.get()
    client = top.Client_Entry.get()
    exchange = top.Exchange_Entry.get()
    counter_party = top.Counter_Party_Entry.get()
    symbol_description = top.Symbol_Description_Entry.get()
    price_instruction = top.Price_Instruction_Entry.get()
    client_description = top.Client_Description_Entry.get()
    account = top.Account_Entry.get()
    limit = top.Limit_Entry.get()
    tif = top.TIF_Entry.get()
    tif_date = top.TIF_Date_Entry.get()
    '''
    print(top.Symbol_Menu_Var.get())

    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import buy
    buy.vp_start_gui()




