#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#    Apr 20, 2019 12:03:25 AM IST  platform: Linux

import sys
from functools import partial

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import order_fill_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Main_Toplevel (root)
    order_fill_support.init(root, top)
    root.mainloop()

w = None
def create_Main_Toplevel(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Main_Toplevel (w)
    order_fill_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Main_Toplevel():
    global w
    w.destroy()
    w = None

class Main_Toplevel:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("600x450+440+156")
        top.title("Testing (to be replaced by Order and Fill Grids)")
        top.configure(background="#000000")
        top.configure(highlightcolor="black")

        self.Buy_Button = tk.Button(top)
        self.Buy_Button.place(relx=0.333, rely=0.4, height=28, width=69)
        self.Buy_Button.configure(background="#1616d8")

        buy_handler = partial(order_fill_support.buy_handler, self, top)

        self.Buy_Button.configure(command=buy_handler)
        self.Buy_Button.configure(text='''Buy''')

        self.Sell_Button = tk.Button(top)
        self.Sell_Button.place(relx=0.525, rely=0.4, height=28, width=69)
        self.Sell_Button.configure(background="#d80f37")

        sell_handler = partial(order_fill_support.sell_handler, self, top)

        self.Sell_Button.configure(command=sell_handler)
        self.Sell_Button.configure(text='''Sell''')

        self.Modify_Button = tk.Button(top)
        self.Modify_Button.place(relx=0.333, rely=0.556, height=28, width=69)
        self.Modify_Button.configure(background="#7f7f7f")

        modify_handler = partial(order_fill_support.modify_handler, self, top)

        self.Modify_Button.configure(command=modify_handler)
        self.Modify_Button.configure(text='''Modify''')

        self.Cancel_Button = tk.Button(top)
        self.Cancel_Button.place(relx=0.525, rely=0.556, height=28, width=69)

        cancel_handler = partial(order_fill_support.cancel_handler, self, top)

        self.Cancel_Button.configure(command=cancel_handler)
        self.Cancel_Button.configure(text='''Cancel''')

if __name__ == '__main__':
    vp_start_gui()





