#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#    Apr 19, 2019 07:01:59 PM IST  platform: Linux

import sys
from functools import partial

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import password_no_match_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Password_No_Match (root)
    password_no_match_support.init(root, top)
    root.mainloop()

w = None
def create_Password_No_Match(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Password_No_Match (w)
    password_no_match_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Password_No_Match():
    global w
    w.destroy()
    w = None

class Password_No_Match:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("300x100+540+293")
        top.title("Error")
        top.configure(background="#ff243a")
        top.configure(highlightcolor="black")

        self.Password_No_Match_Label = tk.Label(top)
        self.Password_No_Match_Label.place(relx=0.133, rely=0.2, height=18
                , width=205)
        self.Password_No_Match_Label.configure(activebackground="#fcfcfc")
        self.Password_No_Match_Label.configure(background="#4f4f4f")
        self.Password_No_Match_Label.configure(text='''Passwords don't match''')

        self.Password_No_Match_OK_Button = tk.Button(top)
        self.Password_No_Match_OK_Button.place(relx=0.4, rely=0.55, height=28
                , width=45)
        self.Password_No_Match_OK_Button.configure(activebackground="#f9f9f9")
        self.Password_No_Match_OK_Button.configure(background="#969696")

        password_no_match_handler = \
        partial(password_no_match_support.password_no_match_handler, self, top)

        self.Password_No_Match_OK_Button.configure(command=password_no_match_handler)
        self.Password_No_Match_OK_Button.configure(text='''OK''')

if __name__ == '__main__':
    vp_start_gui()





