#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#    Apr 19, 2019 12:36:15 PM IST  platform: Linux

import sys
from functools import partial

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import signup_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Signup_Toplevel (root)
    signup_support.init(root, top)
    root.mainloop()

w = None
def create_Signup_Toplevel(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Signup_Toplevel (w)
    signup_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Signup_Toplevel():
    global w
    w.destroy()
    w = None

class Signup_Toplevel:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("600x450+441+156")
        top.title("Signup")
        top.configure(background="#000000")
        top.configure(highlightcolor="black")

        self.Submit_Signup_Button = tk.Button(top)
        self.Submit_Signup_Button.place(relx=0.392, rely=0.678, height=28
                , width=111)
        self.Submit_Signup_Button.configure(activebackground="#ccc8cc")
        self.Submit_Signup_Button.configure(background="#353535")

        submit_signup_handler = partial(signup_support.submit_signup_handler,
                self, top)

        self.Submit_Signup_Button.configure(command=submit_signup_handler)
        self.Submit_Signup_Button.configure(state='active')
        self.Submit_Signup_Button.configure(text='''Submit''')

        self.Confirm_Password_Label = tk.Label(top)
        self.Confirm_Password_Label.place(relx=0.275, rely=0.533, height=18
                , width=246)
        self.Confirm_Password_Label.configure(activebackground="#f9f9f9")
        self.Confirm_Password_Label.configure(background="#5b5b5b")
        self.Confirm_Password_Label.configure(foreground="#ffffff")
        self.Confirm_Password_Label.configure(text='''Confirm Password''')

        self.Confirm_Password_Entry = tk.Entry(top)
        self.Confirm_Password_Entry.place(relx=0.275, rely=0.567, height=20
                , relwidth=0.41)
        self.Confirm_Password_Entry.configure(background="#919191")
        self.Confirm_Password_Entry.configure(font="TkFixedFont")
        self.Confirm_Password_Entry.configure(selectbackground="#c4c4c4")
        self.Confirm_Password_Entry.configure(show="*")

        self.Enter_Password_Label = tk.Label(top)
        self.Enter_Password_Label.place(relx=0.275, rely=0.389, height=18
                , width=246)
        self.Enter_Password_Label.configure(activebackground="#f9f9f9")
        self.Enter_Password_Label.configure(background="#5b5b5b")
        self.Enter_Password_Label.configure(foreground="#ffffff")
        self.Enter_Password_Label.configure(text='''Enter Password''')

        self.Enter_Username_Label = tk.Label(top)
        self.Enter_Username_Label.place(relx=0.275, rely=0.244, height=18
                , width=246)
        self.Enter_Username_Label.configure(activebackground="#f9f9f9")
        self.Enter_Username_Label.configure(background="#5b5b5b")
        self.Enter_Username_Label.configure(foreground="#ffffff")
        self.Enter_Username_Label.configure(text='''Enter Username''')

        self.Enter_Password_Entry = tk.Entry(top)
        self.Enter_Password_Entry.place(relx=0.275, rely=0.422, height=20
                , relwidth=0.41)
        self.Enter_Password_Entry.configure(background="#919191")
        self.Enter_Password_Entry.configure(font="TkFixedFont")
        self.Enter_Password_Entry.configure(selectbackground="#c4c4c4")
        self.Enter_Password_Entry.configure(show="*")

        self.Enter_Username_Entry = tk.Entry(top)
        self.Enter_Username_Entry.place(relx=0.275, rely=0.278, height=20
                , relwidth=0.41)
        self.Enter_Username_Entry.configure(background="#919191")
        self.Enter_Username_Entry.configure(font="TkFixedFont")
        self.Enter_Username_Entry.configure(selectbackground="#c4c4c4")

if __name__ == '__main__':
    vp_start_gui()





