#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#    Apr 19, 2019 12:25:16 PM IST  platform: Linux
#    Apr 19, 2019 12:33:35 PM IST  platform: Linux

import sys
# import order_fill
import tab_new
import password_no_match
import username_exists

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def submit_signup_handler(top, root):
    # print('signup_support.submit_signup_handler')

    username = top.Enter_Username_Entry.get()
    password = top.Enter_Password_Entry.get()
    confirm_password = top.Confirm_Password_Entry.get()

    exists = 0
    with open('users.csv', 'r') as uf:
        for line in uf:
            usrnm, pswd = line.split(',')
            if usrnm == username:
                exists = 1

    if exists == 1:
        root.destroy()
        root = tk.Tk()
        username_exists_tl = username_exists.Username_Exists(root)
    else:
        if password != confirm_password:
            root.destroy()
            root = tk.Tk()
            password_no_match_tl = password_no_match.Password_No_Match(root)
        else:
            with open('users.csv', 'a') as uf:
                uf.write(username + ',' + password + '\n')
            root.destroy()
            root = tk.Tk()
            # order_fill_tl = order_fill.Main_Toplevel(root)
            tab_tl = tab_new.Toplevel1(root)

    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import signup
    signup.vp_start_gui()




