#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.18
#  in conjunction with Tcl version 8.6
#    Apr 22, 2019 01:01:21 AM IST  platform: Linux

import sys
from functools import partial

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import tab_new_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    tab_new_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    tab_new_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font10 = "-family {DejaVu Sans Mono} -size 10 -weight normal "  \
            "-slant roman -underline 0 -overstrike 0"
        font11 = "-family {DejaVu Sans} -size 14 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("1366x713")
        top.title("New Toplevel")
        top.configure(highlightcolor="black")

        self.style.configure('TNotebook.Tab', background=_bgcolor)
        self.style.configure('TNotebook.Tab', foreground=_fgcolor)
        self.style.map('TNotebook.Tab', background=
            [('selected', _compcolor), ('active',_ana2color)])
        self.TNotebook1 = ttk.Notebook(top)
        self.TNotebook1.place(relx=0.0, rely=-0.014, relheight=0.99
                , relwidth=0.997)
        self.TNotebook1.configure(width=1362)
        self.TNotebook1.configure(takefocus="")
        self.TNotebook1_t0 = tk.Frame(self.TNotebook1)
        self.TNotebook1.add(self.TNotebook1_t0, padding=3)
        self.TNotebook1.tab(0, text="Order",compound="left",underline="-1",)
        self.TNotebook1_t0.configure(background="#000000")
        self.TNotebook1_t0.configure(highlightbackground="#69fff0")
        self.TNotebook1_t0.configure(highlightthickness="2")
        self.TNotebook1_t1 = tk.Frame(self.TNotebook1)
        self.TNotebook1.add(self.TNotebook1_t1, padding=3)
        self.TNotebook1.tab(1, text="Trade Management", compound="left"
                ,underline="-1", )
        self.TNotebook1_t1.configure(highlightbackground="#000000")
        self.TNotebook1_t2 = tk.Frame(self.TNotebook1)
        self.TNotebook1.add(self.TNotebook1_t2, padding=3)
        self.TNotebook1.tab(2, text="P&L",compound="top",underline="-1",)
        self.TNotebook1_t2.configure(background="#000000")
        self.TNotebook1_t2.configure(highlightbackground="#69fff0")
        self.TNotebook1_t2.configure(highlightthickness="2")

        self.Save = tk.Button(self.TNotebook1_t0)
        self.Save.place(relx=0.007, rely=0.007, height=29, width=219)
        self.Save.configure(activebackground="#d9d9d9")
        self.Save.configure(background="#666346")
        self.Save.configure(foreground="#efd035")
        self.Save.configure(text='''Save''')

        self.Logout = tk.Button(self.TNotebook1_t0)
        self.Logout.place(relx=0.838, rely=0.007, height=29, width=209)
        self.Logout.configure(activebackground="#d9d9d9")
        self.Logout.configure(background="#666346")
        self.Logout.configure(foreground="#efd035")
        self.Logout.configure(text='''Logout''')

        self.Buy = tk.Button(self.TNotebook1_t0)
        self.Buy.place(relx=0.221, rely=0.007, height=29, width=369)
        self.Buy.configure(activebackground="#d9d9d9")
        self.Buy.configure(background="#69fff0")

        buy = partial(tab_new_support.buy_handler, self, top)

        # self.Buy.configure(command = buy.vp_start_gui,text='''BUY''')
        self.Buy.configure(command=buy, text='''Buy''')

        self.Sell = tk.Button(self.TNotebook1_t0)
        self.Sell.place(relx=0.5, rely=0.007, height=29, width=369)
        self.Sell.configure(activebackground="#d9d9d9")
        self.Sell.configure(background="#69fff0")

        sell = partial(tab_new_support.sell_handler, self, top)

        # self.Sell.configure(command = sell.vp_start_gui,text='''SELL''')
        self.Sell.configure(command=sell, text='''Sell''')

        self.Labelframe4 = tk.LabelFrame(self.TNotebook1_t0)
        self.Labelframe4.place(relx=0.007, rely=0.074, relheight=0.551
                , relwidth=0.985)
        self.Labelframe4.configure(relief='groove')
        self.Labelframe4.configure(font=font11)
        self.Labelframe4.configure(foreground="#f4972c")
        self.Labelframe4.configure(labelanchor="n")
        self.Labelframe4.configure(text='''Order Grid''')
        self.Labelframe4.configure(background="#000000")
        self.Labelframe4.configure(width=1340)

        self.Modify = tk.Button(self.Labelframe4)
        self.Modify.place(relx=0.007, rely=0.053, height=29, width=119
                , bordermode='ignore')
        self.Modify.configure(activebackground="#d9d9d9")
        self.Modify.configure(background="#f4972c")

        modify = partial(tab_new_support.modify_handler, self, top)

        # self.Modify.configure(command = modify.vp_start_gui,text='''Modify''')
        self.Modify.configure(command=modify, text='''Modify''')

        self.Cancel = tk.Button(self.Labelframe4)
        self.Cancel.place(relx=0.093, rely=0.053, height=29, width=129
                , bordermode='ignore')
        self.Cancel.configure(activebackground="#d9d9d9")
        self.Cancel.configure(background="#f4972c")

        cancel = partial(tab_new_support.cancel_handler, self, top)

        # self.Cancel.configure(command = vp_start_gui,text='''Cancel''')
        self.Cancel.configure(command=cancel, text='''Cancel''')

        self.Listbox2 = tk.Listbox(self.Labelframe4)
        self.Listbox2.place(relx=0.0, rely=0.373, relheight=0.789, relwidth=0.055
                , bordermode='ignore')
        self.Listbox2.configure(background="#000000")
        self.Listbox2.configure(font=font10)
        self.Listbox2.configure(foreground="#ffffff")
        self.Listbox2.configure(selectbackground="#c4c4c4")
        self.Listbox2.configure(width=74)

        self.Listbox1 = tk.Listbox(self.Labelframe4)
        self.Listbox1.place(relx=0.056, rely=0.373, relheight=0.789
                , relwidth=0.048, bordermode='ignore')
        self.Listbox1.configure(background="#000000")
        self.Listbox1.configure(font=font10)
        self.Listbox1.configure(foreground="#ffffff")
        self.Listbox1.configure(selectbackground="#c4c4c4")
        self.Listbox1.configure(width=64)

        self.Listbox3 = tk.Listbox(self.Labelframe4)
        self.Listbox3.place(relx=0.16, rely=0.373, relheight=0.789
                , relwidth=0.055, bordermode='ignore')
        self.Listbox3.configure(background="#000000")
        self.Listbox3.configure(font=font10)
        self.Listbox3.configure(foreground="#ffffff")
        self.Listbox3.configure(selectbackground="#c4c4c4")
        self.Listbox3.configure(width=74)

        self.Listbox4 = tk.Listbox(self.Labelframe4)
        self.Listbox4.place(relx=0.213, rely=0.373, relheight=0.789
                , relwidth=0.055, bordermode='ignore')
        self.Listbox4.configure(background="#000000")
        self.Listbox4.configure(font=font10)
        self.Listbox4.configure(foreground="#ffffff")
        self.Listbox4.configure(selectbackground="#c4c4c4")
        self.Listbox4.configure(width=74)

        self.Listbox5 = tk.Listbox(self.Labelframe4)
        self.Listbox5.place(relx=0.392, rely=0.373, relheight=0.736
                , relwidth=0.063, bordermode='ignore')
        self.Listbox5.configure(background="#000000")
        self.Listbox5.configure(font=font10)
        self.Listbox5.configure(foreground="#ffffff")
        self.Listbox5.configure(selectbackground="#c4c4c4")
        self.Listbox5.configure(width=84)

        self.Listbox6 = tk.Listbox(self.Labelframe4)
        self.Listbox6.place(relx=0.332, rely=0.373, relheight=0.736
                , relwidth=0.063, bordermode='ignore')
        self.Listbox6.configure(background="#000000")
        self.Listbox6.configure(font=font10)
        self.Listbox6.configure(foreground="#ffffff")
        self.Listbox6.configure(selectbackground="#c4c4c4")
        self.Listbox6.configure(width=84)

        self.Listbox7 = tk.Listbox(self.Labelframe4)
        self.Listbox7.place(relx=0.269, rely=0.373, relheight=0.789
                , relwidth=0.063, bordermode='ignore')
        self.Listbox7.configure(background="#000000")
        self.Listbox7.configure(font=font10)
        self.Listbox7.configure(foreground="#ffffff")
        self.Listbox7.configure(selectbackground="#c4c4c4")
        self.Listbox7.configure(width=84)

        self.Listbox8 = tk.Listbox(self.Labelframe4)
        self.Listbox8.place(relx=0.104, rely=0.373, relheight=0.789
                , relwidth=0.055, bordermode='ignore')
        self.Listbox8.configure(background="#000000")
        self.Listbox8.configure(font=font10)
        self.Listbox8.configure(foreground="#ffffff")
        self.Listbox8.configure(selectbackground="#c4c4c4")
        self.Listbox8.configure(width=74)

        self.Listbox5 = tk.Listbox(self.Labelframe4)
        self.Listbox5.place(relx=0.455, rely=0.36, relheight=0.736
                , relwidth=0.063, bordermode='ignore')
        self.Listbox5.configure(background="#000000")
        self.Listbox5.configure(font=font10)
        self.Listbox5.configure(foreground="#ffffff")
        self.Listbox5.configure(selectbackground="#c4c4c4")
        self.Listbox5.configure(width=84)

        self.Listbox5 = tk.Listbox(self.Labelframe4)
        self.Listbox5.place(relx=0.519, rely=0.36, relheight=0.736, relwidth=0.07
                , bordermode='ignore')
        self.Listbox5.configure(background="#000000")
        self.Listbox5.configure(font=font10)
        self.Listbox5.configure(foreground="#ffffff")
        self.Listbox5.configure(selectbackground="#c4c4c4")
        self.Listbox5.configure(width=94)

        self.Listbox5 = tk.Listbox(self.Labelframe4)
        self.Listbox5.place(relx=0.59, rely=0.373, relheight=0.736
                , relwidth=0.063, bordermode='ignore')
        self.Listbox5.configure(background="#000000")
        self.Listbox5.configure(font=font10)
        self.Listbox5.configure(foreground="#ffffff")
        self.Listbox5.configure(selectbackground="#c4c4c4")
        self.Listbox5.configure(width=84)

        self.Listbox5 = tk.Listbox(self.Labelframe4)
        self.Listbox5.place(relx=0.653, rely=0.373, relheight=0.736
                , relwidth=0.063, bordermode='ignore')
        self.Listbox5.configure(background="#000000")
        self.Listbox5.configure(font=font10)
        self.Listbox5.configure(foreground="#ffffff")
        self.Listbox5.configure(selectbackground="#c4c4c4")
        self.Listbox5.configure(width=84)

        self.Listbox5 = tk.Listbox(self.Labelframe4)
        self.Listbox5.place(relx=0.716, rely=0.373, relheight=0.736
                , relwidth=0.085, bordermode='ignore')
        self.Listbox5.configure(background="#000000")
        self.Listbox5.configure(font=font10)
        self.Listbox5.configure(foreground="#ffffff")
        self.Listbox5.configure(selectbackground="#c4c4c4")
        self.Listbox5.configure(width=114)

        self.Listbox5 = tk.Listbox(self.Labelframe4)
        self.Listbox5.place(relx=0.795, rely=0.373, relheight=0.736
                , relwidth=0.07, bordermode='ignore')
        self.Listbox5.configure(background="#000000")
        self.Listbox5.configure(font=font10)
        self.Listbox5.configure(foreground="#ffffff")
        self.Listbox5.configure(selectbackground="#c4c4c4")
        self.Listbox5.configure(width=94)

        self.Listbox5 = tk.Listbox(self.Labelframe4)
        self.Listbox5.place(relx=0.866, rely=0.373, relheight=0.736
                , relwidth=0.063, bordermode='ignore')
        self.Listbox5.configure(background="#000000")
        self.Listbox5.configure(font=font10)
        self.Listbox5.configure(foreground="#ffffff")
        self.Listbox5.configure(selectbackground="#c4c4c4")
        self.Listbox5.configure(width=84)

        self.Listbox5 = tk.Listbox(self.Labelframe4)
        self.Listbox5.place(relx=0.925, rely=0.373, relheight=0.736
                , relwidth=0.063, bordermode='ignore')
        self.Listbox5.configure(background="#000000")
        self.Listbox5.configure(font=font10)
        self.Listbox5.configure(foreground="#ffffff")
        self.Listbox5.configure(selectbackground="#c4c4c4")
        self.Listbox5.configure(width=84)

        self.Side = tk.Label(self.Labelframe4)
        self.Side.place(relx=-0.007, rely=0.32, height=21, width=102
                , bordermode='ignore')
        self.Side.configure(activebackground="#f9f9f9")
        self.Side.configure(background="#000000")
        self.Side.configure(foreground="#54e8e8")
        self.Side.configure(text='''Side''')

        self.State = tk.Label(self.Labelframe4)
        self.State.place(relx=0.06, rely=0.32, height=21, width=68
                , bordermode='ignore')
        self.State.configure(activebackground="#f9f9f9")
        self.State.configure(background="#000000")
        self.State.configure(foreground="#54e8e8")
        self.State.configure(text='''State''')

        self.Client = tk.Label(self.Labelframe4)
        self.Client.place(relx=0.104, rely=0.32, height=21, width=72
                , bordermode='ignore')
        self.Client.configure(activebackground="#f9f9f9")
        self.Client.configure(background="#000000")
        self.Client.configure(foreground="#54e8e8")
        self.Client.configure(text='''Client''')

        self.Size = tk.Label(self.Labelframe4)
        self.Size.place(relx=0.157, rely=0.32, height=21, width=81
                , bordermode='ignore')
        self.Size.configure(activebackground="#f9f9f9")
        self.Size.configure(background="#000000")
        self.Size.configure(foreground="#54e8e8")
        self.Size.configure(text='''Size''')

        self.QtyDone = tk.Label(self.Labelframe4)
        self.QtyDone.place(relx=0.209, rely=0.32, height=21, width=91
                , bordermode='ignore')
        self.QtyDone.configure(activebackground="#f9f9f9")
        self.QtyDone.configure(background="#000000")
        self.QtyDone.configure(foreground="#54e8e8")
        self.QtyDone.configure(text='''QtyDone''')

        self.OrderId = tk.Label(self.Labelframe4)
        self.OrderId.place(relx=0.276, rely=0.32, height=21, width=82
                , bordermode='ignore')
        self.OrderId.configure(activebackground="#f9f9f9")
        self.OrderId.configure(background="#000000")
        self.OrderId.configure(foreground="#54e8e8")
        self.OrderId.configure(text='''OrderId''')

        self.PriceInst = tk.Label(self.Labelframe4)
        self.PriceInst.place(relx=0.328, rely=0.32, height=21, width=94
                , bordermode='ignore')
        self.PriceInst.configure(activebackground="#f9f9f9")
        self.PriceInst.configure(background="#000000")
        self.PriceInst.configure(foreground="#54e8e8")
        self.PriceInst.configure(text='''Price Inst''')

        self.Price = tk.Label(self.Labelframe4)
        self.Price.place(relx=0.396, rely=0.32, height=21, width=86
                , bordermode='ignore')
        self.Price.configure(activebackground="#f9f9f9")
        self.Price.configure(background="#000000")
        self.Price.configure(foreground="#54e8e8")
        self.Price.configure(text='''Price''')

        self.Exchange = tk.Label(self.Labelframe4)
        self.Exchange.place(relx=0.455, rely=0.32, height=21, width=99
                , bordermode='ignore')
        self.Exchange.configure(activebackground="#f9f9f9")
        self.Exchange.configure(background="#000000")
        self.Exchange.configure(foreground="#54e8e8")
        self.Exchange.configure(text='''Exchange''')

        self.Product = tk.Label(self.Labelframe4)
        self.Product.place(relx=0.522, rely=0.32, height=21, width=99
                , bordermode='ignore')
        self.Product.configure(activebackground="#f9f9f9")
        self.Product.configure(background="#000000")
        self.Product.configure(foreground="#54e8e8")
        self.Product.configure(text='''Product''')

        self.Ask = tk.Label(self.Labelframe4)
        self.Ask.place(relx=0.59, rely=0.32, height=21, width=89
                , bordermode='ignore')
        self.Ask.configure(activebackground="#f9f9f9")
        self.Ask.configure(background="#000000")
        self.Ask.configure(foreground="#54e8e8")
        self.Ask.configure(text='''Ask''')

        self.Bid = tk.Label(self.Labelframe4)
        self.Bid.place(relx=0.649, rely=0.32, height=21, width=99
                , bordermode='ignore')
        self.Bid.configure(activebackground="#f9f9f9")
        self.Bid.configure(background="#000000")
        self.Bid.configure(foreground="#54e8e8")
        self.Bid.configure(text='''Bid''')

        self.LTP = tk.Label(self.Labelframe4)
        self.LTP.place(relx=0.716, rely=0.32, height=21, width=109
                , bordermode='ignore')
        self.LTP.configure(activebackground="#f9f9f9")
        self.LTP.configure(background="#000000")
        self.LTP.configure(foreground="#54e8e8")
        self.LTP.configure(text='''LTP''')

        self.CounterParty = tk.Label(self.Labelframe4)
        self.CounterParty.place(relx=0.791, rely=0.32, height=21, width=109
                , bordermode='ignore')
        self.CounterParty.configure(activebackground="#f9f9f9")
        self.CounterParty.configure(background="#000000")
        self.CounterParty.configure(foreground="#54e8e8")
        self.CounterParty.configure(text='''Counter Party''')

        self.OrderStamp = tk.Label(self.Labelframe4)
        self.OrderStamp.place(relx=0.866, rely=0.32, height=21, width=99
                , bordermode='ignore')
        self.OrderStamp.configure(activebackground="#f9f9f9")
        self.OrderStamp.configure(background="#000000")
        self.OrderStamp.configure(foreground="#54e8e8")
        self.OrderStamp.configure(text='''Order Stamp''')

        self.Usename = tk.Label(self.Labelframe4)
        self.Usename.place(relx=0.933, rely=0.32, height=21, width=99
                , bordermode='ignore')
        self.Usename.configure(activebackground="#f9f9f9")
        self.Usename.configure(background="#000000")
        self.Usename.configure(foreground="#54e8e8")
        self.Usename.configure(text='''Username''')

        self.Labelframe5 = tk.LabelFrame(self.TNotebook1_t0)
        self.Labelframe5.place(relx=0.0, rely=0.647, relheight=0.316
                , relwidth=0.993)
        self.Labelframe5.configure(relief='groove')
        self.Labelframe5.configure(foreground="#e0e02d")
        self.Labelframe5.configure(text='''Fill''')
        self.Labelframe5.configure(width=1350)

        self.Labelframe4 = tk.LabelFrame(self.TNotebook1_t0)
        self.Labelframe4.place(relx=0.0, rely=0.0, relheight=0.001
                , relwidth=0.001)
        self.Labelframe4.configure(relief='groove')
        self.Labelframe4.configure(font=font10)
        self.Labelframe4.configure(text='''Labelframe''')
        self.Labelframe4.configure(width=1340)

        self.Button17 = tk.Button(self.Labelframe4)
        self.Button17.place(relx=0.0, rely=0.0, height=1, width=1
                , bordermode='ignore')
        self.Button17.configure(activebackground="#d9d9d9")
        self.Button17.configure(text='''Button''')

        self.Button18 = tk.Button(self.Labelframe4)
        self.Button18.place(relx=0.0, rely=0.0, height=1, width=1
                , bordermode='ignore')
        self.Button18.configure(activebackground="#d9d9d9")
        self.Button18.configure(text='''Button''')

        self.tNo44_t0_lab144_lis105 = tk.Listbox(self.Labelframe4)
        self.tNo44_t0_lab144_lis105.place(relx=0.0, rely=0.0, relheight=1.0
                , relwidth=1.0, bordermode='ignore')
        self.tNo44_t0_lab144_lis105.configure(background="white")
        self.tNo44_t0_lab144_lis105.configure(font=font10)
        self.tNo44_t0_lab144_lis105.configure(selectbackground="#c4c4c4")
        self.tNo44_t0_lab144_lis105.configure(width=74)

    @staticmethod
    def popup9(event, *args, **kwargs):
        Popupmenu9 = tk.Menu(root, tearoff=0)
        Popupmenu9.configure(activebackground="#f9f9f9")
        Popupmenu9.post(event.x_root, event.y_root)

    @staticmethod
    def popup10(event, *args, **kwargs):
        Popupmenu10 = tk.Menu(root, tearoff=0)
        Popupmenu10.configure(activebackground="#f9f9f9")
        Popupmenu10.post(event.x_root, event.y_root)

    @staticmethod
    def popup11(event, *args, **kwargs):
        Popupmenu11 = tk.Menu(root, tearoff=0)
        Popupmenu11.configure(activebackground="#f9f9f9")
        Popupmenu11.post(event.x_root, event.y_root)

if __name__ == '__main__':
    vp_start_gui()





