#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#    Apr 19, 2019 07:02:04 PM IST  platform: Linux

import sys
import signup

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def username_exists_handler(top, root):
    # print('username_exists_support.username_exists_handler')

    root.destroy()
    root = tk.Tk()
    signup_tl = signup.Signup_Toplevel(root)

    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import username_exists
    username_exists.vp_start_gui()




